apiVerision: v1
kind: Template
metadata:
  name: test
  annotations:
    openshift.io/display-name: "Test s2i application"
    description: |-
      Test application to run from s2i generated template.

      Sample Repository: https://github.com/epichiori/s2i-test
    openshift.io/long-description: >-
      "This template rapresent a test to deploy s2i applications for developers"
    iconClass: "icon-openshift"
    tags: "wfp,test,s2i"
    openshift.io/provider-display-name: "World Food Programme" 
    openshift.io/documentation-url: "https://github.com/epichiori/s2i-test"
  message: "Your admin credentials are ${ADMIN_USERNAME}:${ADMIN_PASSWORD}" 

objects:
- kind: Secret
  apiVersion: v1
  metadata:
    name: test-config-secret
    annotations:
      template.openshift.io/base64-expose-password: "{.data['password']}"
  stringData:
    password: bar

- kind: Service
  apiVersion: v1
  metadata:
    name: test
    annotations:
      template.openshift.io/expose-service_ip_port: "{.spec.clusterIP}:{.spec.ports[?(.name==\"web\")].port}"
  spec:
    ports:
    - name: "web"
      port: 8080

- kind: Route
  apiVersion: v1
  metadata:
    name: test
    annotations:
      template.openshift.io/expose-uri: "http://{.spec.host}{.spec.path}"
  spec:
    path: /test 
    to:
      name: test

- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: test
  spec:
    runPolicy: "Serial" 
## GIT source
    source:
      git:
        uri: 'git@github.com:epichiori/s2i-test.git'
        ref: master
    type: Git
## s2i build strategy 
    strategy:
      sourceStrategy:
        from:
          kind: "ImageStreamTag"
          name: "openshift:test"
      incremental: true
## remove for production
      env:
        - name: "BUILD_LOGLEVEL"
          value: "3"
    output:
      to:
        kind: ImageStreamTag
        name: 'test:latest'
      imageLabels:
      - name: "vendor"
        value: "WPF"

- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    labels:
      app: test
    name: test
  spec:
    replicas: 1 
    revisionHistoryLimit: 2
    strategy: 
      type: Rolling
    paused: false 
    minReadySeconds: 0 

    template: 
      metadata:
        labels:
          name: test
      spec:
        containers:
          - name: test
            image: 'openshift:test'
            ports:
              - containerPort: 8080
                protocol: "TCP"
    triggers:
      - type: "ConfigChange" 
      - type: "ImageChange" 
        imageChangeParams:
          automatic: true
          containerNames:
            - test
          from:
            kind: ImageStreamTag
            name: 'openshift:test'
        
parameters:

