kind: Template
metadata:
  name: test
  annotations:
    openshift.io/display-name: Test s2i application
    description: |-
      Test application to run from s2i generated template.

      Sample Repository: https://github.com/epichiori/s2i-test
    openshift.io/long-description: This template rapresent a test to deploy s2i applications for developers
    iconClass: icon-openshift
    tags: wfp,test,s2i
    openshift.io/provider-display-name: World Food Programme
    openshift.io/documentation-url: https://github.com/epichiori/s2i-test
  message: Your admin credentials are ${ADMIN_USERNAME}:${ADMIN_PASSWORD} 

objects:

- apiVersion: v1
  kind: ImageStream
  metadata:
    generation: 1
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    lookupPolicy:
      local: false

- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    failedBuildsHistoryLimit: 5
    output:
      to:
        kind: ImageStreamTag
        name: ${APPLICATION_NAME}:latest
    runPolicy: Serial
## GIT source
    source:
      git:
        uri: "${{GIT_SOURCE}}"
      type: Git
## s2i build strategy 
    strategy:
      sourceStrategy:
        env:
          - name: BUILD_LOGLEVEL
            value: '5'
        from:
          kind: ImageStreamTag
          namespace: openshift
          name: 'test:latest'
        forcePull: true
      incremental: true
    successfulBuildsHistoryLimit: 5
    triggers:
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    generation: 1
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: ${APPLICATION_NAME}
      deploymentconfig: ${APPLICATION_NAME}
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: ${APPLICATION_NAME}
          deploymentconfig: ${APPLICATION_NAME}
      spec:
        containers:
#        - imagePullPolicy: Always
        - name: test
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - test
        from:
          kind: ImageStreamTag
          name: ${APPLICATION_NAME}:latest
      type: ImageChange

- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: ${APPLICATION_NAME}
      deploymentconfig: ${APPLICATION_NAME}
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}

- apiVersion: v1
  kind: Route
  metadata:
    creationTimestamp: null
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    host: ${APPLICATION_NAME}.127.0.0.1.nip.io
    path: /test/test-app/
    port:
      targetPort: 8080-tcp
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: ${APPLICATION_NAME}
      weight: 100
    wildcardPolicy: None

parameters:
  - name:		APPLICATION_NAME
    display name:	Application Name
    description:	The name for the application.
    required:		true
    value:		test

  - name: GIT_SOURCE
    display name: Source code GIT repository URL
    description: 'The Git repository where resides custom source code to build'
    value: https://github.com/epichiori/test-src.git
    required: true

#   - collection: prova
#    options:
#      inputMappings:
#      - fieldName: a
#        value: a-value
#      - fieldName: b
#        value: b-value


